app:
  name: robot
  port: 8905

mysql:
  #  address: rdsh1k329zt5o7kkj9l6o.mysql.rds.aliyuncs.com:3306
  #  username: yk_yuemeihui
  #  password: ymh@yk123456
  #  database: test_91gzt
  address: localhost:3306
  database: vergil
  username: root
  password: 123456

redis:
  address: 127.0.0.1:6379
  #password: 123456
